name: cd

on:
  push:
    branches:
      - main
      - Feature-Develop
      - workflow-patch
  pull_request:
    branches:
      - grupo#5
      - Feature-Develop
      - workflow-patch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construcción del proyecto
        run: mvn clean package

      - name: Ejecutar pruebas
        run: mvn test

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
