name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construcción del proyecto
        run: mvn clean package

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar  # O lo que quieras subir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
